"""
Deck Builder — auto-generates pitch deck slides using python-pptx.
Owner: Sakshi
"""

from pptx import Presentation
from pptx.util import Inches, Pt


class DeckBuilder:
    def __init__(self, template_path: str = None):
        self.template_path = template_path

    def build_deck(self, idea: str, output_path: str = "output_deck.pptx"):
        """
        Skeleton: creates a minimal pptx with title slide.
        TODO (Wk3): auto-populate slides from CEO output.
        """
        prs = Presentation(self.template_path) if self.template_path else Presentation()
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = idea
        slide.placeholders[1].text = "Generated by AutoStartup Simulator — stub"

        prs.save(output_path)
        return output_path


if __name__ == "__main__":
    builder = DeckBuilder()
    path = builder.build_deck("Sample Startup Idea")
    print(f"Deck saved: {path}")